spring:
  application:
    name: survey
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
        hibernate.format_sql : true
    open-in-view: true
    generate-ddl: false
  datasource:
    url: jdbc:mysql://localhost:3306/saas_survey?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
#    url: jdbc:mysql://10.201.2.13:3306/saas_survey?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#    username: mq-user
#    password: redhat
    data: classpath*:/data.sql
    schema: classpath*:/schema.sql
    sql-script-encoding: UTF-8
#    schema-username: db_user
#    schema-password: z5J9OT0urtbfVuRuViK7
    continue-on-error: false
    initialize: true
  mvc:
    throw-exception-if-no-handler-found: true
    log-resolved-exception: true
  data:
    rest:
      base-path: /
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
    remote:
      debug:
        enabled: false
server:
  port: 8783
eureka:
  instance:
    metadata-map:
        description: 问卷系统
        version: ${version}
    appname: survey
    app-group-name: business

logging:
  level: debug
